project:
  type: website
  resources:
    - nbs/images/*

format:
  html:
    theme: solar
    css: styles.css
    toc: true

website:
  title: "Lorem Ipsomething"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    pinned: true
  sidebar:
    style: floating

execute:
  freeze: auto

metadata-files: [nbdev.yml, sidebar.yml]
